using EmployeeManagement.Application.DTOs.Rag;
using EmployeeManagement.Application.DTOs.Vision;
using EmployeeManagement.Application.Interfaces;

namespace EmployeeManagement.Infrastructure.Services;

/// <summary>
/// Bridges Phase F (Vision AI) with Phase C (RAG) — LLaVA describes the
/// image in natural language, then that description is chunked + embedded
/// and stored in DocumentChunks exactly like an uploaded text document.
/// Result: users can ask "show me documents related to the attendance device"
/// and the vector search will find images that LLaVA described as such.
/// </summary>
public class VisionIndexService : IVisionIndexService
{
    private readonly IVisionAnalysisService _visionService;
    private readonly IDocumentService _documentService;

    public VisionIndexService(IVisionAnalysisService visionService, IDocumentService documentService)
    {
        _visionService = visionService;
        _documentService = documentService;
    }

    public async Task<VisionIndexResponseDto> IndexImageAsync(
        VisionIndexRequestDto request, int uploadedByEmployeeId, CancellationToken ct = default)
    {
        // Step 1: ask LLaVA to describe the image in detail
        var analysis = await _visionService.AnalyseAsync(new VisionAnalysisRequestDto
        {
            ImageBase64 = request.ImageBase64,
            MimeType = request.MimeType,
            TaskType = VisionTaskType.GeneralDescription
        }, ct);

        // Step 2: prepend a metadata header so retrieval results are clearly labelled as image-sourced
        var indexableText =
            $"[Image Document: {request.DocumentTitle}]\n\n" +
            $"Visual Description (generated by {analysis.ModelUsed}):\n\n" +
            analysis.Analysis;

        // Step 3: pipe the description into the Phase C document pipeline — identical path to a text upload
        var doc = await _documentService.UploadAndIndexAsync(new UploadDocumentDto
        {
            Title = request.DocumentTitle,
            FileName = request.FileName,
            ContentType = "image/llava-description",
            Content = indexableText
        }, uploadedByEmployeeId, ct);

        return new VisionIndexResponseDto
        {
            DocumentId = doc.Id,
            GeneratedDescription = analysis.Analysis,
            ChunkCount = doc.ChunkCount
        };
    }
}